### ISSUE TITLE
Unresolved reference: CoroutineScope

### ISSUE THREAD

**Issue by tenSunFree** [SIKV/Photos#4]
Unresolved reference: CoroutineScope
<img width="617" alt="2021-10-08_205828" src="https://user-images.githubusercontent.com/23090085/136561361-5291dd73-09f2-46c0-a7be-d6f95420ddc0.png">

Maybe you can try to change the distributionUrl to gradle-6.5-bin
<img width="527" alt="2021-10-08_205642" src="https://user-images.githubusercontent.com/23090085/136561520-7b8f1ef8-e824-4ad6-ba7d-e1b105d5b91a.png">

**Comment by SIKV** [comment]
Should be fixed in [this commit](https://github.com/SIKV/Photos/commit/8209f04a3d4a8319d8c3208bab8938916fa42953).
