### ISSUE TITLE
parameter previewUrl is null

### ISSUE THREAD

**Issue by tenSunFree** [SIKV/Photos#5]
Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter previewUrl
<img width="887" alt="2021-10-10_231845" src="https://user-images.githubusercontent.com/23090085/136702126-8c68b502-558b-4a7d-8e3a-d97f87f74897.png">

imageURL does not exist
<img width="331" alt="2021-10-10_232055" src="https://user-images.githubusercontent.com/23090085/136702213-ccf9f9ea-133c-4b6d-a168-0c6e38b26676.png">

Maybe consider changing to largeImageUrl
<img width="369" alt="2021-10-10_232258" src="https://user-images.githubusercontent.com/23090085/136702298-684f53b7-af75-4d48-9b88-38c2b21ce85f.png">

**Comment by SIKV** [comment]
Sorry for the late response, here's why the imageURL might be null in your case

<img width="807" alt="Screen Shot 2022-02-06 at 21 34 41" src="https://user-images.githubusercontent.com/11236380/152698224-9d519b46-0d0f-4847-b87f-055f5a5db01e.png">

**Comment by SIKV** [comment]
https://github.com/SIKV/Photos/commit/3519f1ce5bb07340286251fef49f16e7bae8912d
